/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export {};
// Shared Models

export interface CancelTaskResponse {
  /** [TaskState] task state */
  state: TaskState;
}

export interface ClashTarget {
  /** group chain */
  group: string;
  /** leaf node */
  leaf: string;
  /** server host */
  server: string;
  /** server port */
  port?: number;
  /** resolved ip */
  resolved_ip: string;
  /** config path */
  config_path?: string;
  /** resolution source */
  source?: string;
}

export interface ConnectivityTestRequest {
  /** [InterfaceRef] interface reference */
  interface: InterfaceRef;
  /** http proxy */
  http_proxy: string;
  /** test profile */
  test_profile: string;
  /** browser path */
  browser_path?: string;
  /** round override */
  rounds?: number;
  /** concurrency override */
  concurrency?: number;
}

export interface CurrentSettingsRequest {
  /** [SavedSettings] settings */
  settings: SavedSettings;
}

export interface DefaultConnectionClose {
  /** logical close code */
  code?: number;
  /** close reason */
  reason?: string;
  /** machine-readable error key */
  error?: string;
}

export interface DetectInterfaceRequest {
  /** route probe */
  probe: string;
  /** fallback route probe */
  fallback_probe: string;
  /** clash api controller */
  controller: string;
  /** clash api secret */
  secret?: string;
  /** clash group */
  group: string;
  /** clash config path */
  config_path?: string;
  /** require current clash node */
  clash_current: boolean;
}

export interface DetectInterfaceResponse {
  /** [ProbeSelection] probe selection */
  selection: ProbeSelection;
  /** [InterfaceInfo] detected interface */
  interface: InterfaceInfo;
  /** recorded original mtu */
  original_mtu: number;
  /** [InterfaceInfo] candidate interfaces */
  candidates: Array<InterfaceInfo>;
}

export interface InterfaceCommandResult {
  /** [InterfaceInfo] interface snapshot */
  interface: InterfaceInfo;
  /** command output */
  output?: string;
  /** recorded original mtu */
  original_mtu?: number;
}

export interface InterfaceInfo {
  /** platform name */
  platform_name: string;
  /** interface name */
  name: string;
  /** interface index */
  index?: string;
  /** current mtu */
  mtu?: number;
  /** gateway */
  gateway?: string;
  /** local address */
  local_address?: string;
  /** interface description */
  description?: string;
}

export interface InterfaceListResponse {
  /** [InterfaceInfo] candidate interfaces */
  interfaces: Array<InterfaceInfo>;
}

export interface InterfaceMtuCommandRequest {
  /** [InterfaceRef] interface reference */
  interface: InterfaceRef;
  /** target mtu */
  mtu: number;
}

export interface InterfaceRef {
  /** platform name */
  platform_name: string;
  /** interface name */
  name: string;
  /** interface index */
  index?: string;
}

export interface InterfaceRefreshRequest {
  /** [InterfaceRef] interface reference */
  interface: InterfaceRef;
}

export interface InterfaceRestoreRequest {
  /** [InterfaceRef] interface reference */
  interface: InterfaceRef;
}

export interface MtuSweepRequest {
  /** [InterfaceRef] interface reference */
  interface: InterfaceRef;
  /** http proxy */
  http_proxy: string;
  /** test profile */
  test_profile: string;
  /** browser path */
  browser_path?: string;
  /** comma separated sweep mtus */
  sweep_mtus: string;
  /** round override */
  rounds?: number;
  /** concurrency override */
  concurrency?: number;
}

export interface ProbeSelection {
  /** probe ip */
  probe_ip: string;
  /** warning */
  warning?: string;
  /** [ClashTarget] resolved clash target */
  target?: ClashTarget;
}

export interface ResolveClashTargetRequest {
  /** clash api controller */
  controller: string;
  /** clash api secret */
  secret?: string;
  /** clash group */
  group: string;
  /** clash config path */
  config_path?: string;
}

export interface SavedSettings {
  /** config schema version */
  version: number;
  /** route probe */
  route_probe: string;
  /** fallback route probe */
  fallback_probe: string;
  /** http proxy */
  http_proxy: string;
  /** clash api */
  clash_api: string;
  /** proxy group */
  proxy_group: string;
  /** clash config path */
  config_path: string;
  /** browser path */
  browser_path: string;
  /** test profile */
  test_profile: string;
  /** [TestTarget] configured test targets */
  test_targets: Array<TestTarget>;
  /** comma separated sweep mtus */
  sweep_mtus: string;
  /** default target mtu */
  target_mtu: number;
}

export interface StartTaskResponse {
  /** [TaskState] task state */
  state: TaskState;
}

export interface SystemStatus {
  /** runtime platform */
  platform_name: string;
  /** whether current process has admin/root privilege */
  is_admin: boolean;
  /** whether persistent MTU is supported */
  supports_persistent_mtu: boolean;
  /** whether a long task is running */
  busy: boolean;
  /** current long task kind */
  current_task_kind?: string;
  /** current long task status */
  current_task_status: string;
}

export interface TaskEventsOpen {

  [key: string]: never;
}

export interface TaskLog {
  /** task kind */
  kind: string;
  /** log line */
  line: string;
  /** event timestamp */
  ts: string;
}

export interface TaskProgress {
  /** task kind */
  kind: string;
  /** completed steps */
  done: number;
  /** total steps */
  total: number;
  /** current step label */
  label: string;
}

export interface TaskState {
  /** task kind */
  kind?: string;
  /** task status */
  status: string;
  /** whether cancellation was requested */
  cancel_requested: boolean;
}

export interface TestTarget {
  /** target name */
  name: string;
  /** target url */
  url: string;
  /** whether target is enabled */
  enabled: boolean;
  /** profiles using this target */
  profiles: Array<string>;
  /** target order */
  order: number;
}

