/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export {};

import type {
  CancelTaskResponse,
  StartTaskResponse,
  TaskLog,
  TaskProgress,
  TaskState,
} from "../../../runtime/types";

// Route Contracts

export type CancelCurrentTaskResponse = CancelTaskResponse;

export type GetCurrentTaskResponse = TaskState;

export type StartConnectivityTestResponse = StartTaskResponse;

export type StartMtuSweepResponse = StartTaskResponse;

export type TaskEventMessage =
  | { type: "state"; data: TaskState }
  | { type: "progress"; data: TaskProgress }
  | { type: "log"; data: TaskLog };

export type TaskEventsResponse = void;

