/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type {
  CancelTaskResponse,
  StartTaskResponse,
  TaskLog,
  TaskProgress,
  TaskState,
} from "../../../runtime/models";


// Route Contracts

export type RspCancelCurrentTask = CancelTaskResponse;

export type RspGetCurrentTask = TaskState;

export type RspStartConnectivityTest = StartTaskResponse;

export type RspStartMtuSweep = StartTaskResponse;

export type RspTaskEvents = void;

export type TaskEventMessage =
  | { type: "state"; data: TaskState }
  | { type: "progress"; data: TaskProgress }
  | { type: "log"; data: TaskLog };



