/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class TasksClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * Get long task state

   * Tags: mtu-tuner
   */

  async getCurrentTask(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.GetCurrentTaskResponse> {
    return this.request<Types.GetCurrentTaskResponse>({
      routeId: "api.tasks.get.current",
      method: "GET",
      path: "/api/tasks/current",
      service: "TasksService",
      operation: "GetCurrentTask",
      namespace: "tasks",
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Subscribe task event stream

   * Tags: mtu-tuner
   */
  subscribeTaskEvents(
    request: {
      open?: Shared.TaskEventsOpen;
      headers?: Record<string, string>;
    } = {},
  ): ApiStreamBridge<Types.TaskEventMessage, Shared.DefaultConnectionClose> {
    return this.openStream<Types.TaskEventMessage, Shared.DefaultConnectionClose>({
      routeId: "api.tasks.stream.events",
      connectionKind: "stream",
      scope: "session",
      delivery: "ordered",
      path: "/api/tasks/events",
      service: "TasksService",
      namespace: "tasks",
      connectMethod: "SubscribeTaskEvents",
      closeMethod: "CloseTaskEvents",
      eventBase: "api_blueprint.stream.api.tasks.stream.events",
      open: request.open as unknown as Record<string, unknown> | undefined,
      headers: request.headers,
    });
  }

  /**
   * Run quick test task

   * Tags: mtu-tuner
   */

  async startConnectivityTest(
    request: {
      json?: Shared.ConnectivityTestRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.StartConnectivityTestResponse> {
    return this.request<Types.StartConnectivityTestResponse>({
      routeId: "api.tasks.post.connectivitytest",
      method: "POST",
      path: "/api/tasks/connectivity-test",
      service: "TasksService",
      operation: "StartConnectivityTest",
      namespace: "tasks",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Run mtu sweep task

   * Tags: mtu-tuner
   */

  async startMtuSweep(
    request: {
      json?: Shared.MtuSweepRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.StartMtuSweepResponse> {
    return this.request<Types.StartMtuSweepResponse>({
      routeId: "api.tasks.post.mtusweep",
      method: "POST",
      path: "/api/tasks/mtu-sweep",
      service: "TasksService",
      operation: "StartMtuSweep",
      namespace: "tasks",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Cancel current task

   * Tags: mtu-tuner
   */

  async cancelCurrentTask(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.CancelCurrentTaskResponse> {
    return this.request<Types.CancelCurrentTaskResponse>({
      routeId: "api.tasks.post.current_cancel",
      method: "POST",
      path: "/api/tasks/current/cancel",
      service: "TasksService",
      operation: "CancelCurrentTask",
      namespace: "tasks",
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

}
