/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../../../runtime/models";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class TasksClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }


  /**
   * Get long task state

   * Tags: mtu-tuner
   */
  async getCurrentTask(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspGetCurrentTask> {
    return this.request<Models.RspGetCurrentTask>({
      method: "GET",
      path: "/api/tasks/current",
      service: "TasksService",
      operation: "GetCurrentTask",
      namespace: "tasks",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Subscribe task event stream

   * Tags: mtu-tuner
   */
  subscribeTaskEvents(
    request: {
      open?: Shared.TaskEventsOpen;
      headers?: Record<string, string>;
    } = {},
  ): ApiStreamBridge<Models.TaskEventMessage, Shared.DefaultConnectionClose> {
    return this.openStream<Models.TaskEventMessage, Shared.DefaultConnectionClose>({
      routeId: "api.tasks.stream.events",
      connectionKind: "stream",
      scope: "session",
      delivery: "ordered",
      path: "/api/tasks/events",
      service: "TasksService",
      namespace: "tasks",
      connectMethod: "SubscribeTaskEvents",
      closeMethod: "CloseTaskEvents",
      eventBase: "api_blueprint.stream.api.tasks.stream.events",
      open: request.open as unknown as Record<string, unknown> | undefined,
      headers: request.headers,
    });
  }


  /**
   * Run quick test task

   * Tags: mtu-tuner
   */
  async startConnectivityTest(
    request: {
      json?: Shared.ConnectivityTestRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspStartConnectivityTest> {
    return this.request<Models.RspStartConnectivityTest>({
      method: "POST",
      path: "/api/tasks/connectivity-test",
      service: "TasksService",
      operation: "StartConnectivityTest",
      namespace: "tasks",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Run mtu sweep task

   * Tags: mtu-tuner
   */
  async startMtuSweep(
    request: {
      json?: Shared.MtuSweepRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspStartMtuSweep> {
    return this.request<Models.RspStartMtuSweep>({
      method: "POST",
      path: "/api/tasks/mtu-sweep",
      service: "TasksService",
      operation: "StartMtuSweep",
      namespace: "tasks",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Cancel current task

   * Tags: mtu-tuner
   */
  async cancelCurrentTask(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspCancelCurrentTask> {
    return this.request<Models.RspCancelCurrentTask>({
      method: "POST",
      path: "/api/tasks/current/cancel",
      service: "TasksService",
      operation: "CancelCurrentTask",
      namespace: "tasks",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
