/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV3Transport } from "../../transport";
import { SettingsClient as SharedSettingsClient } from "../../../../routes/api/settings/client";

export type SettingsClient = SharedSettingsClient;

export function createClient(config: ApiClientConfig = {}): SettingsClient {
  return new SharedSettingsClient({
    ...config,
    transport: config.transport ?? new WailsV3Transport(config),
  }) as SettingsClient;
}
