// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package settings

import (
	sharedprovider "mtu-tuner/internal/views/providers"
	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type SettingsService struct {
	impl                        RouterInterface
	sessions                    wailstransport.ConnectionHub
	getCurrentSettingsExecutor  *sharedprovider.RouteExecutor[any, any, RSP_GetCurrentSettings]
	saveCurrentSettingsExecutor *sharedprovider.RouteExecutor[any, REQ_SaveCurrentSettings_JSON, RSP_SaveCurrentSettings]
}

func newGeneratedSettingsService(impl RouterInterface, dispatcher wailstransport.EventDispatcher) *SettingsService {
	return &SettingsService{
		impl:     impl,
		sessions: wailstransport.NewSocketHub(dispatcher),
		getCurrentSettingsExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "settings",
				Namespace: "settings",
				Service:   "SettingsService",
				Operation: "GetCurrentSettings",
				RouteID:   "api.settings.get.current",
				Path:      "/api/settings/current",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@NoneWrapper",
			impl.GetCurrentSettings,
		),
		saveCurrentSettingsExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "settings",
				Namespace: "settings",
				Service:   "SettingsService",
				Operation: "SaveCurrentSettings",
				RouteID:   "api.settings.put.current",
				Path:      "/api/settings/current",
				Methods:   []string{"PUT"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@NoneWrapper",
			impl.SaveCurrentSettings,
		),
	}
}

func (svc *SettingsService) SetConnectionHub(hub wailstransport.ConnectionHub) {
	if svc == nil || hub == nil {
		return
	}
	svc.sessions = hub
}

func (svc *SettingsService) GetCurrentSettings(
	envelope *INVOKE_GetCurrentSettings,
) (rsp *RSP_GetCurrentSettings, err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_GetCurrentSettings](
		"SettingsService",
		"GetCurrentSettings",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_GetCurrentSettings]{Request: req}
	execErr := svc.getCurrentSettingsExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return response, invokeErr
}

func (svc *SettingsService) SaveCurrentSettings(
	envelope *INVOKE_SaveCurrentSettings,
) (rsp *RSP_SaveCurrentSettings, err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_SaveCurrentSettings_JSON, RSP_SaveCurrentSettings](
		"SettingsService",
		"SaveCurrentSettings",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_SaveCurrentSettings_JSON, RSP_SaveCurrentSettings]{Request: req}
	execErr := svc.saveCurrentSettingsExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return response, invokeErr
}
