// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package settings

import (
	sharedroutes "mtu-tuner/internal/views/routes/api/settings"

	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_GetCurrentSettings = sharedroutes.REQ_GetCurrentSettings
type RSP_GetCurrentSettings = sharedroutes.RSP_GetCurrentSettings
type CTX_GetCurrentSettings = sharedroutes.CTX_GetCurrentSettings

type INVOKE_GetCurrentSettings = wailstransport.InvokeEnvelope[any, any]

type REQ_SaveCurrentSettings = sharedroutes.REQ_SaveCurrentSettings
type RSP_SaveCurrentSettings = sharedroutes.RSP_SaveCurrentSettings
type CTX_SaveCurrentSettings = sharedroutes.CTX_SaveCurrentSettings

type REQ_SaveCurrentSettings_JSON = sharedroutes.REQ_SaveCurrentSettings_JSON

type INVOKE_SaveCurrentSettings = wailstransport.InvokeEnvelope[any, REQ_SaveCurrentSettings_JSON]
