/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../../../runtime/models";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class SystemClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }


  /**
   * Get runtime status

   * Tags: mtu-tuner
   */
  async getSystemStatus(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspGetSystemStatus> {
    return this.request<Models.RspGetSystemStatus>({
      method: "GET",
      path: "/api/system/status",
      service: "SystemService",
      operation: "GetSystemStatus",
      namespace: "system",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
