/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export {};

import type {
  SystemStatus,
} from "../../../runtime/types";

// Route Contracts

export type GetSystemStatusResponse = SystemStatus;

