/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type {
  SystemStatus,
} from "../../../runtime/models";


// Route Contracts

export type RspGetSystemStatus = SystemStatus;

