/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class SystemClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * Get runtime status

   * Tags: mtu-tuner
   */

  async getSystemStatus(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.GetSystemStatusResponse> {
    return this.request<Types.GetSystemStatusResponse>({
      routeId: "api.system.get.status",
      method: "GET",
      path: "/api/system/status",
      service: "SystemService",
      operation: "GetSystemStatus",
      namespace: "system",
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

}
