// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package tasks

import (
	sharedprovider "mtu-tuner/internal/views/providers"
	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type TasksService struct {
	impl                          RouterInterface
	sessions                      wailstransport.ConnectionHub
	getCurrentTaskExecutor        *sharedprovider.RouteExecutor[any, any, RSP_GetCurrentTask]
	taskEventsExecutor            *sharedprovider.RouteExecutor[OPEN_TaskEvents, any, RSP_TaskEvents]
	startConnectivityTestExecutor *sharedprovider.RouteExecutor[any, REQ_StartConnectivityTest_JSON, RSP_StartConnectivityTest]
	startMtuSweepExecutor         *sharedprovider.RouteExecutor[any, REQ_StartMtuSweep_JSON, RSP_StartMtuSweep]
	cancelCurrentTaskExecutor     *sharedprovider.RouteExecutor[any, any, RSP_CancelCurrentTask]
}

func newGeneratedTasksService(impl RouterInterface, dispatcher wailstransport.EventDispatcher) *TasksService {
	return &TasksService{
		impl:     impl,
		sessions: wailstransport.NewSocketHub(dispatcher),
		getCurrentTaskExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "tasks",
				Namespace: "tasks",
				Service:   "TasksService",
				Operation: "GetCurrentTask",
				RouteID:   "api.tasks.get.current",
				Path:      "/api/tasks/current",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.GetCurrentTask,
		),
		taskEventsExecutor: sharedprovider.NewRouteExecutor[
			OPEN_TaskEvents,
			any,
			RSP_TaskEvents,
		](
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "tasks",
				Namespace: "tasks",
				Service:   "TasksService",
				Operation: "TaskEvents",
				RouteID:   "api.tasks.stream.events",
				Path:      "/api/tasks/events",
				Methods:   []string{"STREAM"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope("session"),
			},
			"req",
			nil,
		),
		startConnectivityTestExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "tasks",
				Namespace: "tasks",
				Service:   "TasksService",
				Operation: "StartConnectivityTest",
				RouteID:   "api.tasks.post.connectivitytest",
				Path:      "/api/tasks/connectivity-test",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.StartConnectivityTest,
		),
		startMtuSweepExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "tasks",
				Namespace: "tasks",
				Service:   "TasksService",
				Operation: "StartMtuSweep",
				RouteID:   "api.tasks.post.mtusweep",
				Path:      "/api/tasks/mtu-sweep",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.StartMtuSweep,
		),
		cancelCurrentTaskExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "tasks",
				Namespace: "tasks",
				Service:   "TasksService",
				Operation: "CancelCurrentTask",
				RouteID:   "api.tasks.post.current_cancel",
				Path:      "/api/tasks/current/cancel",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.CancelCurrentTask,
		),
	}
}

func (svc *TasksService) SetConnectionHub(hub wailstransport.ConnectionHub) {
	if svc == nil || hub == nil {
		return
	}
	svc.sessions = hub
}

func (svc *TasksService) GetCurrentTask(
	envelope *INVOKE_GetCurrentTask,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_GetCurrentTask], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_GetCurrentTask](
		"TasksService",
		"GetCurrentTask",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_GetCurrentTask]{Request: req}
	execErr := svc.getCurrentTaskExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *TasksService) SubscribeTaskEvents(
	envelope *CONNECTION_CONNECT_TaskEvents,
) (rsp *wailstransport.SocketSessionDescriptor, err error) {
	req, reqErr := wailstransport.ConnectionOpenEnvelopeToReq(envelope, true)
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[OPEN_TaskEvents, any, RSP_TaskEvents](
		"TasksService",
		"SubscribeTaskEvents",
		wailstransport.ConnectionOpenHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[OPEN_TaskEvents, any, RSP_TaskEvents]{Request: req}
	if err := svc.taskEventsExecutor.Run(ctx); err != nil {
		return nil, err
	}

	openSpec := wailstransport.ConnectionOpenSpec{
		RouteID:            "api.tasks.stream.events",
		EventBase:          "api_blueprint.stream.api.tasks.stream.events",
		Scope:              sharedprovider.ConnectionScope("session"),
		RequestedSessionID: wailstransport.ConnectionOpenEnvelopeSessionID(envelope),
	}
	session, sessionErr := svc.sessions.Open(openSpec)
	if sessionErr != nil {
		err = sessionErr
		return
	}
	session = wailstransport.WrapConnectionSession(session, true)
	stream := sharedprovider.NewStreamSession[OPEN_TaskEvents, TaskEventMessage, CLOSE_TaskEvents](
		req.Q,
		session,
	)
	go func() {
		if runErr := svc.impl.TaskEvents(ctx, stream); runErr != nil {
			_ = session.Abort(1011, runErr.Error())
		}
	}()

	descriptor := session.Descriptor()
	return &descriptor, nil
}

func (svc *TasksService) CloseTaskEvents(request *CONNECTION_CLOSE_TaskEvents) error {
	session, err := svc.sessions.Get(request.SessionID)
	if err != nil {
		return err
	}
	session = wailstransport.WrapConnectionSession(session, true)
	code := request.Code
	if code == 0 {
		code = 1000
	}
	return session.Abort(code, request.Reason)
}

func (svc *TasksService) StartConnectivityTest(
	envelope *INVOKE_StartConnectivityTest,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_StartConnectivityTest], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_StartConnectivityTest_JSON, RSP_StartConnectivityTest](
		"TasksService",
		"StartConnectivityTest",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_StartConnectivityTest_JSON, RSP_StartConnectivityTest]{Request: req}
	execErr := svc.startConnectivityTestExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *TasksService) StartMtuSweep(
	envelope *INVOKE_StartMtuSweep,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_StartMtuSweep], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_StartMtuSweep_JSON, RSP_StartMtuSweep](
		"TasksService",
		"StartMtuSweep",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_StartMtuSweep_JSON, RSP_StartMtuSweep]{Request: req}
	execErr := svc.startMtuSweepExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *TasksService) CancelCurrentTask(
	envelope *INVOKE_CancelCurrentTask,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_CancelCurrentTask], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_CancelCurrentTask](
		"TasksService",
		"CancelCurrentTask",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_CancelCurrentTask]{Request: req}
	execErr := svc.cancelCurrentTaskExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}
