// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package tasks

import (
	sharedroutes "mtu-tuner/internal/views/routes/api/tasks"

	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_GetCurrentTask = sharedroutes.REQ_GetCurrentTask
type RSP_GetCurrentTask = sharedroutes.RSP_GetCurrentTask
type CTX_GetCurrentTask = sharedroutes.CTX_GetCurrentTask

type INVOKE_GetCurrentTask = wailstransport.InvokeEnvelope[any, any]

type REQ_TaskEvents = sharedroutes.REQ_TaskEvents
type RSP_TaskEvents = sharedroutes.RSP_TaskEvents
type CTX_TaskEvents = sharedroutes.CTX_TaskEvents
type OPEN_TaskEvents = sharedroutes.OPEN_TaskEvents

type TaskEventMessage = sharedroutes.TaskEventMessage

type CLOSE_TaskEvents = sharedroutes.CLOSE_TaskEvents

type INVOKE_TaskEvents = wailstransport.InvokeEnvelope[OPEN_TaskEvents, any]

type CONNECTION_CONNECT_TaskEvents = wailstransport.ConnectionOpenEnvelope[OPEN_TaskEvents]
type CONNECTION_CLOSE_TaskEvents = wailstransport.SocketCloseEnvelope

type REQ_StartConnectivityTest = sharedroutes.REQ_StartConnectivityTest
type RSP_StartConnectivityTest = sharedroutes.RSP_StartConnectivityTest
type CTX_StartConnectivityTest = sharedroutes.CTX_StartConnectivityTest

type REQ_StartConnectivityTest_JSON = sharedroutes.REQ_StartConnectivityTest_JSON

type INVOKE_StartConnectivityTest = wailstransport.InvokeEnvelope[any, REQ_StartConnectivityTest_JSON]

type REQ_StartMtuSweep = sharedroutes.REQ_StartMtuSweep
type RSP_StartMtuSweep = sharedroutes.RSP_StartMtuSweep
type CTX_StartMtuSweep = sharedroutes.CTX_StartMtuSweep

type REQ_StartMtuSweep_JSON = sharedroutes.REQ_StartMtuSweep_JSON

type INVOKE_StartMtuSweep = wailstransport.InvokeEnvelope[any, REQ_StartMtuSweep_JSON]

type REQ_CancelCurrentTask = sharedroutes.REQ_CancelCurrentTask
type RSP_CancelCurrentTask = sharedroutes.RSP_CancelCurrentTask
type CTX_CancelCurrentTask = sharedroutes.CTX_CancelCurrentTask

type INVOKE_CancelCurrentTask = wailstransport.InvokeEnvelope[any, any]
