// Code generated by api-blueprint (Golang); DO NOT EDIT.

package types

type InterfaceInfo struct {
	PlatformName string `json:"platform_name" xml:"platform_name" form:"platform_name" binding:"required"`
	Name         string `json:"name" xml:"name" form:"name" binding:"required"`
	Index        string `json:"index,omitempty" xml:"index,omitempty" form:"index,omitempty" binding:"omitempty"`
	Mtu          int    `json:"mtu,omitempty" xml:"mtu,omitempty" form:"mtu,omitempty" binding:"omitempty"`
	Gateway      string `json:"gateway,omitempty" xml:"gateway,omitempty" form:"gateway,omitempty" binding:"omitempty"`
	LocalAddress string `json:"local_address,omitempty" xml:"local_address,omitempty" form:"local_address,omitempty" binding:"omitempty"`
	Description  string `json:"description,omitempty" xml:"description,omitempty" form:"description,omitempty" binding:"omitempty"`
}

type InterfaceListResponse struct {
	Interfaces []*InterfaceInfo `json:"interfaces" xml:"interfaces" form:"interfaces" binding:"required"`
}

type DetectInterfaceRequest struct {
	Probe         string `json:"probe" xml:"probe" form:"probe" binding:"required"`
	FallbackProbe string `json:"fallback_probe" xml:"fallback_probe" form:"fallback_probe" binding:"required"`
	Controller    string `json:"controller" xml:"controller" form:"controller" binding:"required"`
	Secret        string `json:"secret,omitempty" xml:"secret,omitempty" form:"secret,omitempty" binding:"omitempty"`
	Group         string `json:"group" xml:"group" form:"group" binding:"required"`
	ConfigPath    string `json:"config_path,omitempty" xml:"config_path,omitempty" form:"config_path,omitempty" binding:"omitempty"`
	ClashCurrent  bool   `json:"clash_current" xml:"clash_current" form:"clash_current" binding:"required"`
}

type ClashTarget struct {
	Group      string `json:"group" xml:"group" form:"group" binding:"required"`
	Leaf       string `json:"leaf" xml:"leaf" form:"leaf" binding:"required"`
	Server     string `json:"server" xml:"server" form:"server" binding:"required"`
	Port       int    `json:"port,omitempty" xml:"port,omitempty" form:"port,omitempty" binding:"omitempty"`
	ResolvedIp string `json:"resolved_ip" xml:"resolved_ip" form:"resolved_ip" binding:"required"`
	ConfigPath string `json:"config_path,omitempty" xml:"config_path,omitempty" form:"config_path,omitempty" binding:"omitempty"`
	Source     string `json:"source,omitempty" xml:"source,omitempty" form:"source,omitempty" binding:"omitempty"`
}

type ProbeSelection struct {
	ProbeIp string       `json:"probe_ip" xml:"probe_ip" form:"probe_ip" binding:"required"`
	Warning string       `json:"warning,omitempty" xml:"warning,omitempty" form:"warning,omitempty" binding:"omitempty"`
	Target  *ClashTarget `json:"target,omitempty" xml:"target,omitempty" form:"target,omitempty" binding:"omitempty"`
}

type DetectInterfaceResponse struct {
	Selection   *ProbeSelection  `json:"selection" xml:"selection" form:"selection" binding:"required"`
	Interface   *InterfaceInfo   `json:"interface" xml:"interface" form:"interface" binding:"required"`
	OriginalMtu int              `json:"original_mtu" xml:"original_mtu" form:"original_mtu" binding:"required"`
	Candidates  []*InterfaceInfo `json:"candidates" xml:"candidates" form:"candidates" binding:"required"`
}

type ResolveClashTargetRequest struct {
	Controller string `json:"controller" xml:"controller" form:"controller" binding:"required"`
	Secret     string `json:"secret,omitempty" xml:"secret,omitempty" form:"secret,omitempty" binding:"omitempty"`
	Group      string `json:"group" xml:"group" form:"group" binding:"required"`
	ConfigPath string `json:"config_path,omitempty" xml:"config_path,omitempty" form:"config_path,omitempty" binding:"omitempty"`
}

type InterfaceRef struct {
	PlatformName string `json:"platform_name" xml:"platform_name" form:"platform_name" binding:"required"`
	Name         string `json:"name" xml:"name" form:"name" binding:"required"`
	Index        string `json:"index,omitempty" xml:"index,omitempty" form:"index,omitempty" binding:"omitempty"`
}

type InterfaceRefreshRequest struct {
	Interface *InterfaceRef `json:"interface" xml:"interface" form:"interface" binding:"required"`
}

type InterfaceCommandResult struct {
	Interface   *InterfaceInfo `json:"interface" xml:"interface" form:"interface" binding:"required"`
	Output      string         `json:"output,omitempty" xml:"output,omitempty" form:"output,omitempty" binding:"omitempty"`
	OriginalMtu int            `json:"original_mtu,omitempty" xml:"original_mtu,omitempty" form:"original_mtu,omitempty" binding:"omitempty"`
}

type InterfaceMtuCommandRequest struct {
	Interface *InterfaceRef `json:"interface" xml:"interface" form:"interface" binding:"required"`
	Mtu       int           `json:"mtu" xml:"mtu" form:"mtu" binding:"required"`
}

type InterfaceRestoreRequest struct {
	Interface *InterfaceRef `json:"interface" xml:"interface" form:"interface" binding:"required"`
}

type TestTarget struct {
	Name     string   `json:"name" xml:"name" form:"name" binding:"required"`
	Url      string   `json:"url" xml:"url" form:"url" binding:"required"`
	Enabled  bool     `json:"enabled" xml:"enabled" form:"enabled" binding:"required"`
	Profiles []string `json:"profiles" xml:"profiles" form:"profiles" binding:"required"`
	Order    int      `json:"order" xml:"order" form:"order" binding:"required"`
}

type SavedSettings struct {
	Version       int           `json:"version" xml:"version" form:"version" binding:"required"`
	RouteProbe    string        `json:"route_probe" xml:"route_probe" form:"route_probe" binding:"required"`
	FallbackProbe string        `json:"fallback_probe" xml:"fallback_probe" form:"fallback_probe" binding:"required"`
	HttpProxy     string        `json:"http_proxy" xml:"http_proxy" form:"http_proxy" binding:"required"`
	ClashApi      string        `json:"clash_api" xml:"clash_api" form:"clash_api" binding:"required"`
	ProxyGroup    string        `json:"proxy_group" xml:"proxy_group" form:"proxy_group" binding:"required"`
	ConfigPath    string        `json:"config_path" xml:"config_path" form:"config_path" binding:"required"`
	BrowserPath   string        `json:"browser_path" xml:"browser_path" form:"browser_path" binding:"required"`
	TestProfile   string        `json:"test_profile" xml:"test_profile" form:"test_profile" binding:"required"`
	TestTargets   []*TestTarget `json:"test_targets" xml:"test_targets" form:"test_targets" binding:"required"`
	SweepMtus     string        `json:"sweep_mtus" xml:"sweep_mtus" form:"sweep_mtus" binding:"required"`
	TargetMtu     int           `json:"target_mtu" xml:"target_mtu" form:"target_mtu" binding:"required"`
}

type CurrentSettingsRequest struct {
	Settings *SavedSettings `json:"settings" xml:"settings" form:"settings" binding:"required"`
}

type SystemStatus struct {
	PlatformName          string `json:"platform_name" xml:"platform_name" form:"platform_name" binding:"required"`
	IsAdmin               bool   `json:"is_admin" xml:"is_admin" form:"is_admin" binding:"required"`
	SupportsPersistentMtu bool   `json:"supports_persistent_mtu" xml:"supports_persistent_mtu" form:"supports_persistent_mtu" binding:"required"`
	Busy                  bool   `json:"busy" xml:"busy" form:"busy" binding:"required"`
	CurrentTaskKind       string `json:"current_task_kind,omitempty" xml:"current_task_kind,omitempty" form:"current_task_kind,omitempty" binding:"omitempty"`
	CurrentTaskStatus     string `json:"current_task_status" xml:"current_task_status" form:"current_task_status" binding:"required"`
}

type TaskState struct {
	Kind            string `json:"kind,omitempty" xml:"kind,omitempty" form:"kind,omitempty" binding:"omitempty"`
	Status          string `json:"status" xml:"status" form:"status" binding:"required"`
	CancelRequested bool   `json:"cancel_requested" xml:"cancel_requested" form:"cancel_requested" binding:"required"`
}

type TaskEventsOpen struct {
}

type TaskProgress struct {
	Kind  string `json:"kind" xml:"kind" form:"kind" binding:"required"`
	Done  int    `json:"done" xml:"done" form:"done" binding:"required"`
	Total int    `json:"total" xml:"total" form:"total" binding:"required"`
	Label string `json:"label" xml:"label" form:"label" binding:"required"`
}

type TaskLog struct {
	Kind string `json:"kind" xml:"kind" form:"kind" binding:"required"`
	Line string `json:"line" xml:"line" form:"line" binding:"required"`
	Ts   string `json:"ts" xml:"ts" form:"ts" binding:"required"`
}

type DefaultConnectionClose struct {
	Code   int    `json:"code,omitempty" xml:"code,omitempty" form:"code,omitempty" binding:"omitempty"`
	Reason string `json:"reason,omitempty" xml:"reason,omitempty" form:"reason,omitempty" binding:"omitempty"`
	Error  string `json:"error,omitempty" xml:"error,omitempty" form:"error,omitempty" binding:"omitempty"`
}

type ConnectivityTestRequest struct {
	Interface   *InterfaceRef `json:"interface" xml:"interface" form:"interface" binding:"required"`
	HttpProxy   string        `json:"http_proxy" xml:"http_proxy" form:"http_proxy" binding:"required"`
	TestProfile string        `json:"test_profile" xml:"test_profile" form:"test_profile" binding:"required"`
	BrowserPath string        `json:"browser_path,omitempty" xml:"browser_path,omitempty" form:"browser_path,omitempty" binding:"omitempty"`
	Rounds      int           `json:"rounds,omitempty" xml:"rounds,omitempty" form:"rounds,omitempty" binding:"omitempty"`
	Concurrency int           `json:"concurrency,omitempty" xml:"concurrency,omitempty" form:"concurrency,omitempty" binding:"omitempty"`
}

type StartTaskResponse struct {
	State *TaskState `json:"state" xml:"state" form:"state" binding:"required"`
}

type MtuSweepRequest struct {
	Interface   *InterfaceRef `json:"interface" xml:"interface" form:"interface" binding:"required"`
	HttpProxy   string        `json:"http_proxy" xml:"http_proxy" form:"http_proxy" binding:"required"`
	TestProfile string        `json:"test_profile" xml:"test_profile" form:"test_profile" binding:"required"`
	BrowserPath string        `json:"browser_path,omitempty" xml:"browser_path,omitempty" form:"browser_path,omitempty" binding:"omitempty"`
	SweepMtus   string        `json:"sweep_mtus" xml:"sweep_mtus" form:"sweep_mtus" binding:"required"`
	Rounds      int           `json:"rounds,omitempty" xml:"rounds,omitempty" form:"rounds,omitempty" binding:"omitempty"`
	Concurrency int           `json:"concurrency,omitempty" xml:"concurrency,omitempty" form:"concurrency,omitempty" binding:"omitempty"`
}

type CancelTaskResponse struct {
	State *TaskState `json:"state" xml:"state" form:"state" binding:"required"`
}
