/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV3Transport } from "../../transport";
import { SystemClient as SharedSystemClient } from "../../../../routes/api/system/client";

export type SystemClient = SharedSystemClient;

export function createClient(config: ApiClientConfig = {}): SystemClient {
  return new SharedSystemClient({
    ...config,
    transport: config.transport ?? new WailsV3Transport(config),
  }) as SystemClient;
}
