/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

export const WAILS_V3_BINDINGS: Record<string, string> = {
  "network.NetworkService.ApplyInterfaceMtu": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.ApplyInterfaceMtu",
  "network.NetworkService.DetectInterface": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.DetectInterface",
  "network.NetworkService.ListInterfaces": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.ListInterfaces",
  "network.NetworkService.PersistInterfaceMtu": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.PersistInterfaceMtu",
  "network.NetworkService.RefreshInterface": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.RefreshInterface",
  "network.NetworkService.ResolveClashTarget": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.ResolveClashTarget",
  "network.NetworkService.RestoreInterfaceMtu": "mtu-tuner/internal/views/transports/wailsv3/api/network.NetworkService.RestoreInterfaceMtu",
  "settings.SettingsService.GetCurrentSettings": "mtu-tuner/internal/views/transports/wailsv3/api/settings.SettingsService.GetCurrentSettings",
  "settings.SettingsService.SaveCurrentSettings": "mtu-tuner/internal/views/transports/wailsv3/api/settings.SettingsService.SaveCurrentSettings",
  "system.SystemService.GetSystemStatus": "mtu-tuner/internal/views/transports/wailsv3/api/system.SystemService.GetSystemStatus",
  "tasks.TasksService.CancelCurrentTask": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.CancelCurrentTask",
  "tasks.TasksService.CloseTaskEvents": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.CloseTaskEvents",
  "tasks.TasksService.GetCurrentTask": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.GetCurrentTask",
  "tasks.TasksService.StartConnectivityTest": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.StartConnectivityTest",
  "tasks.TasksService.StartMtuSweep": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.StartMtuSweep",
  "tasks.TasksService.SubscribeTaskEvents": "mtu-tuner/internal/views/transports/wailsv3/api/tasks.TasksService.SubscribeTaskEvents",
};
