// Code generated by api-blueprint (Golang); DO NOT EDIT.

package settings

import (
	"fmt"
)

type _GenRouter struct{}

func (impl *_GenRouter) GetCurrentSettings(ctx *CTX_GetCurrentSettings, req *REQ_GetCurrentSettings) (rsp *RSP_GetCurrentSettings, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) SaveCurrentSettings(ctx *CTX_SaveCurrentSettings, req *REQ_SaveCurrentSettings) (rsp *RSP_SaveCurrentSettings, err error) {
	return nil, fmt.Errorf("not implemented")
}
