// Code generated by api-blueprint (Golang); DO NOT EDIT.

package settings

import (
	providers "mtu-tuner/internal/views/providers"
	protos "mtu-tuner/internal/views/routes/api/_gen_protos"
)

type REQ_GetCurrentSettings = providers.REQ[
	any,
	any,
]

type RSP_GetCurrentSettings_BODY = protos.SavedSettings

type RSP_GetCurrentSettings = RSP_GetCurrentSettings_BODY

type CTX_GetCurrentSettings = providers.Context[
	any,
	any,
	RSP_GetCurrentSettings_BODY,
]

type REQ_SaveCurrentSettings_JSON = protos.CurrentSettingsRequest

type REQ_SaveCurrentSettings = providers.REQ[
	any,
	REQ_SaveCurrentSettings_JSON,
]

type RSP_SaveCurrentSettings_BODY = protos.SavedSettings

type RSP_SaveCurrentSettings = RSP_SaveCurrentSettings_BODY

type CTX_SaveCurrentSettings = providers.Context[
	any,
	REQ_SaveCurrentSettings_JSON,
	RSP_SaveCurrentSettings_BODY,
]
