// Code generated by api-blueprint (Golang); DO NOT EDIT.

package settings

type RouterInterface interface {
	GetCurrentSettings(ctx *CTX_GetCurrentSettings, req *REQ_GetCurrentSettings) (rsp *RSP_GetCurrentSettings, err error)
	SaveCurrentSettings(ctx *CTX_SaveCurrentSettings, req *REQ_SaveCurrentSettings) (rsp *RSP_SaveCurrentSettings, err error)
}
