// Code generated by api-blueprint (Golang); DO NOT EDIT.

package api

import (
	"mtu-tuner/internal/views/routes/api/network"
	"mtu-tuner/internal/views/routes/api/settings"
	"mtu-tuner/internal/views/routes/api/system"
	"mtu-tuner/internal/views/routes/api/tasks"
)

type Blueprint struct {
	NetworkRouter  *network.Router
	SettingsRouter *settings.Router
	SystemRouter   *system.Router
	TasksRouter    *tasks.Router
}

func NewBlueprint() *Blueprint {
	return &Blueprint{
		NetworkRouter:  network.NewRouter(),
		SettingsRouter: settings.NewRouter(),
		SystemRouter:   system.NewRouter(),
		TasksRouter:    tasks.NewRouter(),
	}
}
