/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../../runtime/client";
import type { NetworkClient } from "./network/client";
import { createClient as createNetworkClient } from "./network/client";
import type { SettingsClient } from "./settings/client";
import { createClient as createSettingsClient } from "./settings/client";
import type { SystemClient } from "./system/client";
import { createClient as createSystemClient } from "./system/client";
import type { TasksClient } from "./tasks/client";
import { createClient as createTasksClient } from "./tasks/client";

export interface GeneratedClients {
  networkClient: NetworkClient;
  settingsClient: SettingsClient;
  systemClient: SystemClient;
  tasksClient: TasksClient;
}

export function createClients(config: ApiClientConfig = {}): GeneratedClients {
  return {
    networkClient: createNetworkClient(config),
    settingsClient: createSettingsClient(config),
    systemClient: createSystemClient(config),
    tasksClient: createTasksClient(config),
  };
}
