// Code generated by api-blueprint (Golang); DO NOT EDIT.

package network

import (
	"fmt"
)

type _GenRouter struct{}

func (impl *_GenRouter) ListInterfaces(ctx *CTX_ListInterfaces, req *REQ_ListInterfaces) (rsp *RSP_ListInterfaces, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) DetectInterface(ctx *CTX_DetectInterface, req *REQ_DetectInterface) (rsp *RSP_DetectInterface, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) ResolveClashTarget(ctx *CTX_ResolveClashTarget, req *REQ_ResolveClashTarget) (rsp *RSP_ResolveClashTarget, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) RefreshInterface(ctx *CTX_RefreshInterface, req *REQ_RefreshInterface) (rsp *RSP_RefreshInterface, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) ApplyInterfaceMtu(ctx *CTX_ApplyInterfaceMtu, req *REQ_ApplyInterfaceMtu) (rsp *RSP_ApplyInterfaceMtu, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) RestoreInterfaceMtu(ctx *CTX_RestoreInterfaceMtu, req *REQ_RestoreInterfaceMtu) (rsp *RSP_RestoreInterfaceMtu, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) PersistInterfaceMtu(ctx *CTX_PersistInterfaceMtu, req *REQ_PersistInterfaceMtu) (rsp *RSP_PersistInterfaceMtu, err error) {
	return nil, fmt.Errorf("not implemented")
}
