// Code generated by api-blueprint (Golang); DO NOT EDIT.

package network

type RouterInterface interface {
	ListInterfaces(ctx *CTX_ListInterfaces, req *REQ_ListInterfaces) (rsp *RSP_ListInterfaces, err error)
	DetectInterface(ctx *CTX_DetectInterface, req *REQ_DetectInterface) (rsp *RSP_DetectInterface, err error)
	ResolveClashTarget(ctx *CTX_ResolveClashTarget, req *REQ_ResolveClashTarget) (rsp *RSP_ResolveClashTarget, err error)
	RefreshInterface(ctx *CTX_RefreshInterface, req *REQ_RefreshInterface) (rsp *RSP_RefreshInterface, err error)
	ApplyInterfaceMtu(ctx *CTX_ApplyInterfaceMtu, req *REQ_ApplyInterfaceMtu) (rsp *RSP_ApplyInterfaceMtu, err error)
	RestoreInterfaceMtu(ctx *CTX_RestoreInterfaceMtu, req *REQ_RestoreInterfaceMtu) (rsp *RSP_RestoreInterfaceMtu, err error)
	PersistInterfaceMtu(ctx *CTX_PersistInterfaceMtu, req *REQ_PersistInterfaceMtu) (rsp *RSP_PersistInterfaceMtu, err error)
}
