// Code generated by api-blueprint (Golang); DO NOT EDIT.

package network

import (
	providers "mtu-tuner/internal/views/providers"
	protos "mtu-tuner/internal/views/routes/api/_gen_protos"
)

type REQ_ListInterfaces = providers.REQ[
	any,
	any,
]

type RSP_ListInterfaces_BODY = protos.InterfaceListResponse

type RSP_ListInterfaces = RSP_ListInterfaces_BODY

type CTX_ListInterfaces = providers.Context[
	any,
	any,
	RSP_ListInterfaces_BODY,
]

type REQ_DetectInterface_JSON = protos.DetectInterfaceRequest

type REQ_DetectInterface = providers.REQ[
	any,
	REQ_DetectInterface_JSON,
]

type RSP_DetectInterface_BODY = protos.DetectInterfaceResponse

type RSP_DetectInterface = RSP_DetectInterface_BODY

type CTX_DetectInterface = providers.Context[
	any,
	REQ_DetectInterface_JSON,
	RSP_DetectInterface_BODY,
]

type REQ_ResolveClashTarget_JSON = protos.ResolveClashTargetRequest

type REQ_ResolveClashTarget = providers.REQ[
	any,
	REQ_ResolveClashTarget_JSON,
]

type RSP_ResolveClashTarget_BODY = protos.ClashTarget

type RSP_ResolveClashTarget = RSP_ResolveClashTarget_BODY

type CTX_ResolveClashTarget = providers.Context[
	any,
	REQ_ResolveClashTarget_JSON,
	RSP_ResolveClashTarget_BODY,
]

type REQ_RefreshInterface_JSON = protos.InterfaceRefreshRequest

type REQ_RefreshInterface = providers.REQ[
	any,
	REQ_RefreshInterface_JSON,
]

type RSP_RefreshInterface_BODY = protos.InterfaceCommandResult

type RSP_RefreshInterface = RSP_RefreshInterface_BODY

type CTX_RefreshInterface = providers.Context[
	any,
	REQ_RefreshInterface_JSON,
	RSP_RefreshInterface_BODY,
]

type REQ_ApplyInterfaceMtu_JSON = protos.InterfaceMtuCommandRequest

type REQ_ApplyInterfaceMtu = providers.REQ[
	any,
	REQ_ApplyInterfaceMtu_JSON,
]

type RSP_ApplyInterfaceMtu_BODY = protos.InterfaceCommandResult

type RSP_ApplyInterfaceMtu = RSP_ApplyInterfaceMtu_BODY

type CTX_ApplyInterfaceMtu = providers.Context[
	any,
	REQ_ApplyInterfaceMtu_JSON,
	RSP_ApplyInterfaceMtu_BODY,
]

type REQ_RestoreInterfaceMtu_JSON = protos.InterfaceRestoreRequest

type REQ_RestoreInterfaceMtu = providers.REQ[
	any,
	REQ_RestoreInterfaceMtu_JSON,
]

type RSP_RestoreInterfaceMtu_BODY = protos.InterfaceCommandResult

type RSP_RestoreInterfaceMtu = RSP_RestoreInterfaceMtu_BODY

type CTX_RestoreInterfaceMtu = providers.Context[
	any,
	REQ_RestoreInterfaceMtu_JSON,
	RSP_RestoreInterfaceMtu_BODY,
]

type REQ_PersistInterfaceMtu_JSON = protos.InterfaceMtuCommandRequest

type REQ_PersistInterfaceMtu = providers.REQ[
	any,
	REQ_PersistInterfaceMtu_JSON,
]

type RSP_PersistInterfaceMtu_BODY = protos.InterfaceCommandResult

type RSP_PersistInterfaceMtu = RSP_PersistInterfaceMtu_BODY

type CTX_PersistInterfaceMtu = providers.Context[
	any,
	REQ_PersistInterfaceMtu_JSON,
	RSP_PersistInterfaceMtu_BODY,
]
