// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package network

import (
	sharedprovider "mtu-tuner/internal/views/providers"
	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type NetworkService struct {
	impl                        RouterInterface
	sessions                    wailstransport.ConnectionHub
	listInterfacesExecutor      *sharedprovider.RouteExecutor[any, any, RSP_ListInterfaces]
	detectInterfaceExecutor     *sharedprovider.RouteExecutor[any, REQ_DetectInterface_JSON, RSP_DetectInterface]
	resolveClashTargetExecutor  *sharedprovider.RouteExecutor[any, REQ_ResolveClashTarget_JSON, RSP_ResolveClashTarget]
	refreshInterfaceExecutor    *sharedprovider.RouteExecutor[any, REQ_RefreshInterface_JSON, RSP_RefreshInterface]
	applyInterfaceMtuExecutor   *sharedprovider.RouteExecutor[any, REQ_ApplyInterfaceMtu_JSON, RSP_ApplyInterfaceMtu]
	restoreInterfaceMtuExecutor *sharedprovider.RouteExecutor[any, REQ_RestoreInterfaceMtu_JSON, RSP_RestoreInterfaceMtu]
	persistInterfaceMtuExecutor *sharedprovider.RouteExecutor[any, REQ_PersistInterfaceMtu_JSON, RSP_PersistInterfaceMtu]
}

func newGeneratedNetworkService(impl RouterInterface, dispatcher wailstransport.EventDispatcher) *NetworkService {
	return &NetworkService{
		impl:     impl,
		sessions: wailstransport.NewSocketHub(dispatcher),
		listInterfacesExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "ListInterfaces",
				RouteID:   "api.network.get.interfaces",
				Path:      "/api/network/interfaces",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.ListInterfaces,
		),
		detectInterfaceExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "DetectInterface",
				RouteID:   "api.network.post.detect",
				Path:      "/api/network/detect",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.DetectInterface,
		),
		resolveClashTargetExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "ResolveClashTarget",
				RouteID:   "api.network.post.clashtarget_resolve",
				Path:      "/api/network/clash-target/resolve",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.ResolveClashTarget,
		),
		refreshInterfaceExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "RefreshInterface",
				RouteID:   "api.network.post.interface_refresh",
				Path:      "/api/network/interface/refresh",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.RefreshInterface,
		),
		applyInterfaceMtuExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "ApplyInterfaceMtu",
				RouteID:   "api.network.post.interface_mtu_apply",
				Path:      "/api/network/interface/mtu/apply",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.ApplyInterfaceMtu,
		),
		restoreInterfaceMtuExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "RestoreInterfaceMtu",
				RouteID:   "api.network.post.interface_mtu_restore",
				Path:      "/api/network/interface/mtu/restore",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.RestoreInterfaceMtu,
		),
		persistInterfaceMtuExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "network",
				Namespace: "network",
				Service:   "NetworkService",
				Operation: "PersistInterfaceMtu",
				RouteID:   "api.network.post.interface_mtu_persist",
				Path:      "/api/network/interface/mtu/persist",
				Methods:   []string{"POST"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req=J|handle|rsp=json@CodeMessageDataEnvelope",
			impl.PersistInterfaceMtu,
		),
	}
}

func (svc *NetworkService) SetConnectionHub(hub wailstransport.ConnectionHub) {
	if svc == nil || hub == nil {
		return
	}
	svc.sessions = hub
}

func (svc *NetworkService) ListInterfaces(
	envelope *INVOKE_ListInterfaces,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_ListInterfaces], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_ListInterfaces](
		"NetworkService",
		"ListInterfaces",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_ListInterfaces]{Request: req}
	execErr := svc.listInterfacesExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) DetectInterface(
	envelope *INVOKE_DetectInterface,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_DetectInterface], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_DetectInterface_JSON, RSP_DetectInterface](
		"NetworkService",
		"DetectInterface",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_DetectInterface_JSON, RSP_DetectInterface]{Request: req}
	execErr := svc.detectInterfaceExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) ResolveClashTarget(
	envelope *INVOKE_ResolveClashTarget,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_ResolveClashTarget], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_ResolveClashTarget_JSON, RSP_ResolveClashTarget](
		"NetworkService",
		"ResolveClashTarget",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_ResolveClashTarget_JSON, RSP_ResolveClashTarget]{Request: req}
	execErr := svc.resolveClashTargetExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) RefreshInterface(
	envelope *INVOKE_RefreshInterface,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_RefreshInterface], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_RefreshInterface_JSON, RSP_RefreshInterface](
		"NetworkService",
		"RefreshInterface",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_RefreshInterface_JSON, RSP_RefreshInterface]{Request: req}
	execErr := svc.refreshInterfaceExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) ApplyInterfaceMtu(
	envelope *INVOKE_ApplyInterfaceMtu,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_ApplyInterfaceMtu], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_ApplyInterfaceMtu_JSON, RSP_ApplyInterfaceMtu](
		"NetworkService",
		"ApplyInterfaceMtu",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_ApplyInterfaceMtu_JSON, RSP_ApplyInterfaceMtu]{Request: req}
	execErr := svc.applyInterfaceMtuExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) RestoreInterfaceMtu(
	envelope *INVOKE_RestoreInterfaceMtu,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_RestoreInterfaceMtu], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_RestoreInterfaceMtu_JSON, RSP_RestoreInterfaceMtu](
		"NetworkService",
		"RestoreInterfaceMtu",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_RestoreInterfaceMtu_JSON, RSP_RestoreInterfaceMtu]{Request: req}
	execErr := svc.restoreInterfaceMtuExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}

func (svc *NetworkService) PersistInterfaceMtu(
	envelope *INVOKE_PersistInterfaceMtu,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_PersistInterfaceMtu], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_PersistInterfaceMtu_JSON, RSP_PersistInterfaceMtu](
		"NetworkService",
		"PersistInterfaceMtu",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, REQ_PersistInterfaceMtu_JSON, RSP_PersistInterfaceMtu]{Request: req}
	execErr := svc.persistInterfaceMtuExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}
