// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package network

import (
	sharedroutes "mtu-tuner/internal/views/routes/api/network"

	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_ListInterfaces = sharedroutes.REQ_ListInterfaces
type RSP_ListInterfaces = sharedroutes.RSP_ListInterfaces
type CTX_ListInterfaces = sharedroutes.CTX_ListInterfaces

type INVOKE_ListInterfaces = wailstransport.InvokeEnvelope[any, any]

type REQ_DetectInterface = sharedroutes.REQ_DetectInterface
type RSP_DetectInterface = sharedroutes.RSP_DetectInterface
type CTX_DetectInterface = sharedroutes.CTX_DetectInterface

type REQ_DetectInterface_JSON = sharedroutes.REQ_DetectInterface_JSON

type INVOKE_DetectInterface = wailstransport.InvokeEnvelope[any, REQ_DetectInterface_JSON]

type REQ_ResolveClashTarget = sharedroutes.REQ_ResolveClashTarget
type RSP_ResolveClashTarget = sharedroutes.RSP_ResolveClashTarget
type CTX_ResolveClashTarget = sharedroutes.CTX_ResolveClashTarget

type REQ_ResolveClashTarget_JSON = sharedroutes.REQ_ResolveClashTarget_JSON

type INVOKE_ResolveClashTarget = wailstransport.InvokeEnvelope[any, REQ_ResolveClashTarget_JSON]

type REQ_RefreshInterface = sharedroutes.REQ_RefreshInterface
type RSP_RefreshInterface = sharedroutes.RSP_RefreshInterface
type CTX_RefreshInterface = sharedroutes.CTX_RefreshInterface

type REQ_RefreshInterface_JSON = sharedroutes.REQ_RefreshInterface_JSON

type INVOKE_RefreshInterface = wailstransport.InvokeEnvelope[any, REQ_RefreshInterface_JSON]

type REQ_ApplyInterfaceMtu = sharedroutes.REQ_ApplyInterfaceMtu
type RSP_ApplyInterfaceMtu = sharedroutes.RSP_ApplyInterfaceMtu
type CTX_ApplyInterfaceMtu = sharedroutes.CTX_ApplyInterfaceMtu

type REQ_ApplyInterfaceMtu_JSON = sharedroutes.REQ_ApplyInterfaceMtu_JSON

type INVOKE_ApplyInterfaceMtu = wailstransport.InvokeEnvelope[any, REQ_ApplyInterfaceMtu_JSON]

type REQ_RestoreInterfaceMtu = sharedroutes.REQ_RestoreInterfaceMtu
type RSP_RestoreInterfaceMtu = sharedroutes.RSP_RestoreInterfaceMtu
type CTX_RestoreInterfaceMtu = sharedroutes.CTX_RestoreInterfaceMtu

type REQ_RestoreInterfaceMtu_JSON = sharedroutes.REQ_RestoreInterfaceMtu_JSON

type INVOKE_RestoreInterfaceMtu = wailstransport.InvokeEnvelope[any, REQ_RestoreInterfaceMtu_JSON]

type REQ_PersistInterfaceMtu = sharedroutes.REQ_PersistInterfaceMtu
type RSP_PersistInterfaceMtu = sharedroutes.RSP_PersistInterfaceMtu
type CTX_PersistInterfaceMtu = sharedroutes.CTX_PersistInterfaceMtu

type REQ_PersistInterfaceMtu_JSON = sharedroutes.REQ_PersistInterfaceMtu_JSON

type INVOKE_PersistInterfaceMtu = wailstransport.InvokeEnvelope[any, REQ_PersistInterfaceMtu_JSON]
