// Code generated by api-blueprint (Golang); DO NOT EDIT.

package tasks

import (
	providers "mtu-tuner/internal/views/providers"
)

type RouterInterface interface {
	GetCurrentTask(ctx *CTX_GetCurrentTask, req *REQ_GetCurrentTask) (rsp *RSP_GetCurrentTask, err error)
	TaskEvents(
		ctx *CTX_TaskEvents,
		stream providers.Stream[OPEN_TaskEvents, TaskEventMessage, CLOSE_TaskEvents],
	) error
	StartConnectivityTest(ctx *CTX_StartConnectivityTest, req *REQ_StartConnectivityTest) (rsp *RSP_StartConnectivityTest, err error)
	StartMtuSweep(ctx *CTX_StartMtuSweep, req *REQ_StartMtuSweep) (rsp *RSP_StartMtuSweep, err error)
	CancelCurrentTask(ctx *CTX_CancelCurrentTask, req *REQ_CancelCurrentTask) (rsp *RSP_CancelCurrentTask, err error)
}
