// Code generated by api-blueprint (Golang); DO NOT EDIT.

package tasks

import (
	"fmt"
	providers "mtu-tuner/internal/views/providers"
)

type _GenRouter struct{}

func (impl *_GenRouter) GetCurrentTask(ctx *CTX_GetCurrentTask, req *REQ_GetCurrentTask) (rsp *RSP_GetCurrentTask, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) TaskEvents(
	ctx *CTX_TaskEvents,
	stream providers.Stream[OPEN_TaskEvents, TaskEventMessage, CLOSE_TaskEvents],
) error {
	return fmt.Errorf("not implemented")
}

func (impl *_GenRouter) StartConnectivityTest(ctx *CTX_StartConnectivityTest, req *REQ_StartConnectivityTest) (rsp *RSP_StartConnectivityTest, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) StartMtuSweep(ctx *CTX_StartMtuSweep, req *REQ_StartMtuSweep) (rsp *RSP_StartMtuSweep, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) CancelCurrentTask(ctx *CTX_CancelCurrentTask, req *REQ_CancelCurrentTask) (rsp *RSP_CancelCurrentTask, err error) {
	return nil, fmt.Errorf("not implemented")
}
