// Code generated by api-blueprint (Golang); DO NOT EDIT.

package tasks

import (
	"encoding/json"

	providers "mtu-tuner/internal/views/providers"
	types "mtu-tuner/internal/views/routes/api/_gen_types"
)

type REQ_GetCurrentTask = providers.REQ[
	any,
	any,
]

type RSP_GetCurrentTask_BODY = types.TaskState

type RSP_GetCurrentTask = RSP_GetCurrentTask_BODY

type CTX_GetCurrentTask = providers.Context[
	any,
	any,
	RSP_GetCurrentTask_BODY,
]

type OPEN_TaskEvents = types.TaskEventsOpen

type REQ_TaskEvents = providers.REQ[
	OPEN_TaskEvents,
	any,
]

type RSP_TaskEvents = any

type CTX_TaskEvents = providers.Context[
	OPEN_TaskEvents,
	any,
	any,
]

type TaskEventMessage_State_DATA = types.TaskState

type TaskEventMessage_Progress_DATA = types.TaskProgress

type TaskEventMessage_Log_DATA = types.TaskLog

type CLOSE_TaskEvents = types.DefaultConnectionClose

type REQ_StartConnectivityTest_JSON = types.ConnectivityTestRequest

type REQ_StartConnectivityTest = providers.REQ[
	any,
	REQ_StartConnectivityTest_JSON,
]

type RSP_StartConnectivityTest_BODY = types.StartTaskResponse

type RSP_StartConnectivityTest = RSP_StartConnectivityTest_BODY

type CTX_StartConnectivityTest = providers.Context[
	any,
	REQ_StartConnectivityTest_JSON,
	RSP_StartConnectivityTest_BODY,
]

type REQ_StartMtuSweep_JSON = types.MtuSweepRequest

type REQ_StartMtuSweep = providers.REQ[
	any,
	REQ_StartMtuSweep_JSON,
]

type RSP_StartMtuSweep_BODY = types.StartTaskResponse

type RSP_StartMtuSweep = RSP_StartMtuSweep_BODY

type CTX_StartMtuSweep = providers.Context[
	any,
	REQ_StartMtuSweep_JSON,
	RSP_StartMtuSweep_BODY,
]

type REQ_CancelCurrentTask = providers.REQ[
	any,
	any,
]

type RSP_CancelCurrentTask_BODY = types.CancelTaskResponse

type RSP_CancelCurrentTask = RSP_CancelCurrentTask_BODY

type CTX_CancelCurrentTask = providers.Context[
	any,
	any,
	RSP_CancelCurrentTask_BODY,
]

type TaskEventMessage struct {
	Type string          `json:"type"`
	Data json.RawMessage `json:"data,omitempty"`
}

const TaskEventMessageTypeState = "state"

func NewTaskEventMessageState(data *TaskEventMessage_State_DATA) (*TaskEventMessage, error) {
	raw, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return &TaskEventMessage{Type: TaskEventMessageTypeState, Data: raw}, nil
}

func (msg *TaskEventMessage) DecodeState() (*TaskEventMessage_State_DATA, error) {
	if msg == nil {
		return nil, nil
	}
	var data TaskEventMessage_State_DATA
	if err := json.Unmarshal(msg.Data, &data); err != nil {
		return nil, err
	}
	return &data, nil
}

const TaskEventMessageTypeProgress = "progress"

func NewTaskEventMessageProgress(data *TaskEventMessage_Progress_DATA) (*TaskEventMessage, error) {
	raw, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return &TaskEventMessage{Type: TaskEventMessageTypeProgress, Data: raw}, nil
}

func (msg *TaskEventMessage) DecodeProgress() (*TaskEventMessage_Progress_DATA, error) {
	if msg == nil {
		return nil, nil
	}
	var data TaskEventMessage_Progress_DATA
	if err := json.Unmarshal(msg.Data, &data); err != nil {
		return nil, err
	}
	return &data, nil
}

const TaskEventMessageTypeLog = "log"

func NewTaskEventMessageLog(data *TaskEventMessage_Log_DATA) (*TaskEventMessage, error) {
	raw, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return &TaskEventMessage{Type: TaskEventMessageTypeLog, Data: raw}, nil
}

func (msg *TaskEventMessage) DecodeLog() (*TaskEventMessage_Log_DATA, error) {
	if msg == nil {
		return nil, nil
	}
	var data TaskEventMessage_Log_DATA
	if err := json.Unmarshal(msg.Data, &data); err != nil {
		return nil, err
	}
	return &data, nil
}
