/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type {
  SavedSettings,
} from "../../../runtime/models";


// Route Contracts

export type RspGetCurrentSettings = SavedSettings;

export type RspSaveCurrentSettings = SavedSettings;

