/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export {};

import type {
  SavedSettings,
} from "../../../runtime/types";

// Route Contracts

export type GetCurrentSettingsResponse = SavedSettings;

export type SaveCurrentSettingsResponse = SavedSettings;

