/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../../../runtime/models";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class SettingsClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }


  /**
   * Load saved settings

   * Tags: mtu-tuner
   */
  async getCurrentSettings(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspGetCurrentSettings> {
    return this.request<Models.RspGetCurrentSettings>({
      method: "GET",
      path: "/api/settings/current",
      service: "SettingsService",
      operation: "GetCurrentSettings",
      namespace: "settings",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Save settings

   * Tags: mtu-tuner
   */
  async saveCurrentSettings(
    request: {
      json?: Shared.CurrentSettingsRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspSaveCurrentSettings> {
    return this.request<Models.RspSaveCurrentSettings>({
      method: "PUT",
      path: "/api/settings/current",
      service: "SettingsService",
      operation: "SaveCurrentSettings",
      namespace: "settings",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
