/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class SettingsClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * Load saved settings

   * Tags: mtu-tuner
   */

  async getCurrentSettings(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.GetCurrentSettingsResponse> {
    return this.request<Types.GetCurrentSettingsResponse>({
      routeId: "api.settings.get.current",
      method: "GET",
      path: "/api/settings/current",
      service: "SettingsService",
      operation: "GetCurrentSettings",
      namespace: "settings",
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Save settings

   * Tags: mtu-tuner
   */

  async saveCurrentSettings(
    request: {
      json?: Shared.CurrentSettingsRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.SaveCurrentSettingsResponse> {
    return this.request<Types.SaveCurrentSettingsResponse>({
      routeId: "api.settings.put.current",
      method: "PUT",
      path: "/api/settings/current",
      service: "SettingsService",
      operation: "SaveCurrentSettings",
      namespace: "settings",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

}
