/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV3Transport } from "../../transport";
import { NetworkClient as SharedNetworkClient } from "../../../../routes/api/network/client";


export type NetworkClient = SharedNetworkClient;


export function createClient(config: ApiClientConfig = {}): NetworkClient {
  return new SharedNetworkClient({
    ...config,
    transport: config.transport ?? new WailsV3Transport(config),
  }) as NetworkClient;
}
