.PHONY: help
help:
	@echo "Common targets:"
	@echo "  mtu-tuner-gui-frontend-build Build the mtu-tuner Wails GUI frontend"
	@echo "  mtu-tuner-gui-build          Build the mtu-tuner Wails GUI binary"
	@echo "  mtu-tuner-gui-build-windows  Cross-build the mtu-tuner GUI for Windows (set WINDOWS_GOARCH/WINDOWS_CC/WINDOWS_CXX as needed)"
	@echo "  mtu-tuner-gui-package-windows Build and package the mtu-tuner Windows GUI into build/packages"
	@echo "  mtu-tuner-gui-run            Build the GUI frontend and run services/mtu_tuner/cmd/gui"
	@echo "  mtu-tuner-test               Run Go tests in services/mtu_tuner (default GO_TEST_FLAGS=$(GO_TEST_FLAGS))"
	@echo "  release-validate             Validate a tool release.toml and optional tag/workflow"
	@echo "  release-version              Print the version from services/<tool>/release.toml"
	@echo "  release-version-show         Alias for release-version"
	@echo "  release-version-stable       Print the stable release tag and optionally check BASE_VERSION"
	@echo "  release-version-rc           Print the RC release tag and optionally check BASE_VERSION"
	@echo "  release-tag                  Print the stable or RC tag for TOOL=..."
	@echo "  release-tag-check            Validate RELEASE_TAG against the tool metadata"
	@echo "  release-metadata             Print validated release metadata as JSON"
	@echo "  release-matrix               Print GitHub Actions matrix JSON for a workflow"
	@echo "  release-workflow-tools       Print the workflow-wide tool verification matrix JSON"
	@echo "  release-workflow-matrix      Print the workflow-wide build matrix JSON across release tools"
	@echo "  release-preflight           Run release metadata tests and the tool short tests for RELEASE_TAG"
	@echo "  release-local               Build and package local-host targets for RELEASE_TAG"
	@echo "  release-package              Package one release target after it has been built"
	@echo ""
	@echo "Common overrides: TOOL=$(TOOL) CMD=$(CMD) BIN_NAME=$(BIN_NAME) GOOS=$(GOOS) GOARCH=$(GOARCH) TARGET=$(TARGET) RC=$(RC) WORKFLOW=$(WORKFLOW) RELEASE_TAG=$(RELEASE_TAG)"
	@echo "API blueprint overrides: API_BLUEPRINT_VERSION=$(API_BLUEPRINT_VERSION) API_BLUEPRINT_PACKAGE=$(API_BLUEPRINT_PACKAGE) API_BLUEPRINT_PROJECT=$(API_BLUEPRINT_PROJECT)"
