// Code generated by api-blueprint (Golang); DO NOT EDIT.

package system

import (
	"fmt"
)

type _GenRouter struct{}

func (impl *_GenRouter) GetSystemStatus(ctx *CTX_GetSystemStatus, req *REQ_GetSystemStatus) (rsp *RSP_GetSystemStatus, err error) {
	return nil, fmt.Errorf("not implemented")
}
