// Code generated by api-blueprint (Golang); DO NOT EDIT.

package system

import (
	providers "mtu-tuner/internal/views/providers"
	types "mtu-tuner/internal/views/routes/api/_gen_types"
)

type REQ_GetSystemStatus = providers.REQ[
	any,
	any,
]

type RSP_GetSystemStatus_BODY = types.SystemStatus

type RSP_GetSystemStatus = RSP_GetSystemStatus_BODY

type CTX_GetSystemStatus = providers.Context[
	any,
	any,
	RSP_GetSystemStatus_BODY,
]
