// Code generated by api-blueprint (Golang); DO NOT EDIT.

package system

type RouterInterface interface {
	GetSystemStatus(ctx *CTX_GetSystemStatus, req *REQ_GetSystemStatus) (rsp *RSP_GetSystemStatus, err error)
}
