/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class NetworkClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * List available interfaces

   * Tags: mtu-tuner
   */

  async listInterfaces(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.ListInterfacesResponse> {
    return this.request<Types.ListInterfacesResponse>({
      routeId: "api.network.get.interfaces",
      method: "GET",
      path: "/api/network/interfaces",
      service: "NetworkService",
      operation: "ListInterfaces",
      namespace: "network",
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Detect route interface

   * Tags: mtu-tuner
   */

  async detectInterface(
    request: {
      json?: Shared.DetectInterfaceRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Shared.DetectInterfaceResponse> {
    return this.request<Shared.DetectInterfaceResponse>({
      routeId: "api.network.post.detect",
      method: "POST",
      path: "/api/network/detect",
      service: "NetworkService",
      operation: "DetectInterface",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Resolve current clash target

   * Tags: mtu-tuner
   */

  async resolveClashTarget(
    request: {
      json?: Shared.ResolveClashTargetRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.ResolveClashTargetResponse> {
    return this.request<Types.ResolveClashTargetResponse>({
      routeId: "api.network.post.clashtarget_resolve",
      method: "POST",
      path: "/api/network/clash-target/resolve",
      service: "NetworkService",
      operation: "ResolveClashTarget",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Refresh current interface mtu

   * Tags: mtu-tuner
   */

  async refreshInterface(
    request: {
      json?: Shared.InterfaceRefreshRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.RefreshInterfaceResponse> {
    return this.request<Types.RefreshInterfaceResponse>({
      routeId: "api.network.post.interface_refresh",
      method: "POST",
      path: "/api/network/interface/refresh",
      service: "NetworkService",
      operation: "RefreshInterface",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Set active mtu

   * Tags: mtu-tuner
   */

  async applyInterfaceMtu(
    request: {
      json?: Shared.InterfaceMtuCommandRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.ApplyInterfaceMtuResponse> {
    return this.request<Types.ApplyInterfaceMtuResponse>({
      routeId: "api.network.post.interface_mtu_apply",
      method: "POST",
      path: "/api/network/interface/mtu/apply",
      service: "NetworkService",
      operation: "ApplyInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Restore recorded mtu

   * Tags: mtu-tuner
   */

  async restoreInterfaceMtu(
    request: {
      json?: Shared.InterfaceRestoreRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.RestoreInterfaceMtuResponse> {
    return this.request<Types.RestoreInterfaceMtuResponse>({
      routeId: "api.network.post.interface_mtu_restore",
      method: "POST",
      path: "/api/network/interface/mtu/restore",
      service: "NetworkService",
      operation: "RestoreInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

  /**
   * Set persistent mtu

   * Tags: mtu-tuner
   */

  async persistInterfaceMtu(
    request: {
      json?: Shared.InterfaceMtuCommandRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Types.PersistInterfaceMtuResponse> {
    return this.request<Types.PersistInterfaceMtuResponse>({
      routeId: "api.network.post.interface_mtu_persist",
      method: "POST",
      path: "/api/network/interface/mtu/persist",
      service: "NetworkService",
      operation: "PersistInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs,
    });
  }

}
