/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../../../runtime/models";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class NetworkClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }


  /**
   * List available interfaces

   * Tags: mtu-tuner
   */
  async listInterfaces(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspListInterfaces> {
    return this.request<Models.RspListInterfaces>({
      method: "GET",
      path: "/api/network/interfaces",
      service: "NetworkService",
      operation: "ListInterfaces",
      namespace: "network",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Detect route interface

   * Tags: mtu-tuner
   */
  async detectInterface(
    request: {
      json?: Shared.DetectInterfaceRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspDetectInterface> {
    return this.request<Models.RspDetectInterface>({
      method: "POST",
      path: "/api/network/detect",
      service: "NetworkService",
      operation: "DetectInterface",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Resolve current clash target

   * Tags: mtu-tuner
   */
  async resolveClashTarget(
    request: {
      json?: Shared.ResolveClashTargetRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspResolveClashTarget> {
    return this.request<Models.RspResolveClashTarget>({
      method: "POST",
      path: "/api/network/clash-target/resolve",
      service: "NetworkService",
      operation: "ResolveClashTarget",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Refresh current interface mtu

   * Tags: mtu-tuner
   */
  async refreshInterface(
    request: {
      json?: Shared.InterfaceRefreshRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspRefreshInterface> {
    return this.request<Models.RspRefreshInterface>({
      method: "POST",
      path: "/api/network/interface/refresh",
      service: "NetworkService",
      operation: "RefreshInterface",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Set active mtu

   * Tags: mtu-tuner
   */
  async applyInterfaceMtu(
    request: {
      json?: Shared.InterfaceMtuCommandRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspApplyInterfaceMtu> {
    return this.request<Models.RspApplyInterfaceMtu>({
      method: "POST",
      path: "/api/network/interface/mtu/apply",
      service: "NetworkService",
      operation: "ApplyInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Restore recorded mtu

   * Tags: mtu-tuner
   */
  async restoreInterfaceMtu(
    request: {
      json?: Shared.InterfaceRestoreRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspRestoreInterfaceMtu> {
    return this.request<Models.RspRestoreInterfaceMtu>({
      method: "POST",
      path: "/api/network/interface/mtu/restore",
      service: "NetworkService",
      operation: "RestoreInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * Set persistent mtu

   * Tags: mtu-tuner
   */
  async persistInterfaceMtu(
    request: {
      json?: Shared.InterfaceMtuCommandRequest;
      body?: RequestInit["body"];
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspPersistInterfaceMtu> {
    return this.request<Models.RspPersistInterfaceMtu>({
      method: "POST",
      path: "/api/network/interface/mtu/persist",
      service: "NetworkService",
      operation: "PersistInterfaceMtu",
      namespace: "network",
      json: request.json,
      body: request.body,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
