/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export {};

import type {
  ClashTarget,
  InterfaceCommandResult,
  InterfaceListResponse,
} from "../../../runtime/types";

// Route Contracts

export type ApplyInterfaceMtuResponse = InterfaceCommandResult;

export type ListInterfacesResponse = InterfaceListResponse;

export type PersistInterfaceMtuResponse = InterfaceCommandResult;

export type RefreshInterfaceResponse = InterfaceCommandResult;

export type ResolveClashTargetResponse = ClashTarget;

export type RestoreInterfaceMtuResponse = InterfaceCommandResult;

