/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type {
  ClashTarget,
  DetectInterfaceResponse,
  InterfaceCommandResult,
  InterfaceListResponse,
} from "../../../runtime/models";


// Route Contracts

export type RspApplyInterfaceMtu = InterfaceCommandResult;

export type RspDetectInterface = DetectInterfaceResponse;

export type RspListInterfaces = InterfaceListResponse;

export type RspPersistInterfaceMtu = InterfaceCommandResult;

export type RspRefreshInterface = InterfaceCommandResult;

export type RspResolveClashTarget = ClashTarget;

export type RspRestoreInterfaceMtu = InterfaceCommandResult;

