// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package system

import (
	sharedprovider "mtu-tuner/internal/views/providers"
	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type SystemService struct {
	impl                    RouterInterface
	sessions                wailstransport.ConnectionHub
	getSystemStatusExecutor *sharedprovider.RouteExecutor[any, any, RSP_GetSystemStatus]
}

func newGeneratedSystemService(impl RouterInterface, dispatcher wailstransport.EventDispatcher) *SystemService {
	return &SystemService{
		impl:     impl,
		sessions: wailstransport.NewSocketHub(dispatcher),
		getSystemStatusExecutor: sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "system",
				Namespace: "system",
				Service:   "SystemService",
				Operation: "GetSystemStatus",
				RouteID:   "api.system.get.status",
				Path:      "/api/system/status",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportWails,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|handle|rsp=json@CodeMessageDataEnvelope",
			impl.GetSystemStatus,
		),
	}
}

func (svc *SystemService) SetConnectionHub(hub wailstransport.ConnectionHub) {
	if svc == nil || hub == nil {
		return
	}
	svc.sessions = hub
}

func (svc *SystemService) GetSystemStatus(
	envelope *INVOKE_GetSystemStatus,
) (rsp *sharedprovider.RSP_JSON_CodeMessageDataEnvelope[RSP_GetSystemStatus], err error) {
	req, reqErr := wailstransport.EnvelopeToReq(envelope, wailstransport.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_GetSystemStatus](
		"SystemService",
		"GetSystemStatus",
		wailstransport.EnvelopeHeaders(envelope),
	)
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_GetSystemStatus]{Request: req}
	execErr := svc.getSystemStatusExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_CodeMessageDataEnvelope(response, invokeErr), nil
}
