// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package system

import (
	sharedroutes "mtu-tuner/internal/views/routes/api/system"

	wailstransport "mtu-tuner/internal/views/transports/wailsv3"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_GetSystemStatus = sharedroutes.REQ_GetSystemStatus
type RSP_GetSystemStatus = sharedroutes.RSP_GetSystemStatus
type CTX_GetSystemStatus = sharedroutes.CTX_GetSystemStatus

type INVOKE_GetSystemStatus = wailstransport.InvokeEnvelope[any, any]
