/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV3Transport } from "../../transport";
import { TasksClient as SharedTasksClient } from "../../../../routes/api/tasks/client";

export type TasksClient = SharedTasksClient;

export function createClient(config: ApiClientConfig = {}): TasksClient {
  return new SharedTasksClient({
    ...config,
    transport: config.transport ?? new WailsV3Transport(config),
  }) as TasksClient;
}
